@extends('layouts.app')

@section('content')
<section class="hero-gradient text-white"><div class="mx-auto max-w-7xl px-5 py-14"><a href="{{ route('admin.applications.index') }}" class="font-bold text-emerald-200">← Kembali</a><h1 class="mt-4 text-4xl font-black">{{ $application->application_number }}</h1><p class="mt-2 text-blue-100">{{ $application->documentType->name }} · {{ $application->user->name }}</p></div></section>
<section class="pattern"><div class="mx-auto max-w-7xl px-5 py-12">
@if(session('success'))<div class="mb-6 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-700">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mb-6 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{{ $errors->first() }}</div>@endif
<div class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
<div class="rounded-3xl bg-white p-8 shadow-sm"><h2 class="text-2xl font-black text-solo-blue">Data pemohon</h2><dl class="mt-7 grid gap-5 text-base"><div class="border-b border-slate-100 pb-4"><dt class="font-black text-solo-blue">NIK</dt><dd class="mt-1 text-lg text-slate-700">{{ $application->user->citizenProfile?->nik ?: '—' }}</dd></div>@foreach($application->submitted_data ?? [] as $key => $value)@if(!in_array($key, ['note', 'requirements'], true))<div class="border-b border-slate-100 pb-4"><dt class="font-black text-solo-blue">{{ ['applicant_name'=>'Nama lengkap','phone'=>'Nomor telepon','address'=>'Alamat domisili'][$key] ?? ucfirst(str_replace('_', ' ', $key)) }}</dt><dd class="mt-1 text-lg text-slate-700">{{ is_scalar($value) ? (string) $value : json_encode($value) }}</dd></div>@endif @endforeach</dl>
<div class="mt-8 border-t border-slate-200 pt-6"><h2 class="text-2xl font-black text-solo-blue">Berkas persyaratan</h2><div class="mt-4 grid gap-4">@forelse($application->files->where('is_result', false) as $file)<div class="rounded-2xl border border-slate-200 p-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-lg font-black text-slate-800">{{ $file->category }}</p><p class="mt-1 text-base text-slate-500">{{ $file->original_name }}</p></div><div class="flex flex-wrap items-center gap-4"><a class="text-base font-black text-solo-blue" target="_blank" rel="noopener" href="{{ route('admin.files.view', $file) }}">View</a><a class="text-base font-black text-solo-blue" href="{{ route('admin.files.download', $file) }}">Download</a></div></div><div class="mt-4 flex flex-wrap items-center gap-3"><span class="rounded-full px-4 py-1.5 text-sm font-black {{ $file->verification_status === 'verified' ? 'bg-emerald-100 text-emerald-700' : ($file->verification_status === 'rejected' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($file->verification_status) }}</span>@if($file->verification_status === 'pending')<form data-preserve-scroll action="{{ route('admin.files.verify', $file) }}" method="POST">@csrf<input type="hidden" name="verification_status" value="verified"><button type="submit" class="w-full rounded-xl border-2 border-emerald-600 bg-emerald-600 px-5 py-3 text-base font-black text-white shadow-md transition hover:bg-emerald-700 focus:outline-none focus:ring-4 focus:ring-emerald-200">Approve berkas</button></form><button type="button" data-reject-file="{{ $file->id }}" class="rounded-xl border-2 border-red-600 bg-red-600 px-5 py-3 text-base font-black text-white shadow-md transition hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-200">Reject berkas</button><form id="reject-file-{{ $file->id }}" action="{{ route('admin.files.verify', $file) }}" method="POST" class="mt-2 hidden w-full gap-2">@csrf<input type="hidden" name="verification_status" value="rejected"><input name="verification_note" class="flex-1 rounded-lg border-slate-300 px-3 py-2 text-sm" placeholder="Alasan penolakan" required><button type="submit" class="rounded-full bg-red-700 px-4 py-2 text-sm font-black text-white">Kirim</button></form>@endif</div></div>@empty<p class="text-base text-slate-500">Belum ada berkas persyaratan.</p>@endforelse</div></div></div>
<aside class="h-fit rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><div class="flex items-center justify-between gap-3 border-b border-slate-200 pb-5"><div><p class="text-xs font-extrabold uppercase tracking-widest text-solo-green">Workflow DMLS</p><h2 class="mt-1 text-2xl font-black text-solo-blue">Tindakan admin</h2></div><span class="rounded-full bg-blue-100 px-4 py-2 text-sm font-black text-blue-700">{{ ucfirst($application->status) }}</span></div><div class="mt-6 grid gap-4">@if(! in_array($application->status, ['approved', 'completed', 'rejected'], true))<form action="{{ route('admin.applications.approve', $application) }}" method="POST">@csrf<button type="submit" style="display:block;width:100%;padding:16px 24px;border-radius:12px;background:#059669;color:#ffffff;font-weight:900;font-size:14px;letter-spacing:.04em;border:2px solid #047857;box-shadow:0 8px 18px rgba(5,150,105,.28);cursor:pointer;">✓ APPROVE PENGAJUAN</button></form><button type="button" data-reject-application style="display:block;width:100%;padding:16px 24px;border-radius:12px;background:#dc2626;color:#ffffff;font-weight:900;font-size:14px;letter-spacing:.04em;border:2px solid #b91c1c;box-shadow:0 8px 18px rgba(220,38,38,.28);cursor:pointer;">✕&nbsp; REJECT PENGAJUAN</button>@endif</div><form id="reject-application-form" class="mt-5 hidden gap-3 rounded-2xl border border-red-200 bg-red-50 p-4" action="{{ route('admin.applications.reject', $application) }}" method="POST">@csrf<label class="text-sm font-extrabold text-red-900">Alasan penolakan<textarea name="note" rows="3" class="mt-2 w-full rounded-xl border border-red-200 bg-white px-4 py-3 text-sm" placeholder="Tuliskan alasan yang akan dilihat warga" required></textarea></label><button type="submit" class="rounded-xl bg-red-700 px-6 py-3 text-sm font-black text-white shadow transition hover:bg-red-800">Kirim penolakan</button></form>@if(in_array($application->status, ['approved', 'ready'], true))<div class="mt-8 border-t border-slate-200 pt-6"><h3 class="font-black text-slate-800">Upload surat hasil</h3><p class="mt-1 text-sm text-slate-500">PDF ini akan muncul sebagai tombol download di dashboard warga.</p><form class="mt-4 grid gap-4" action="{{ route('admin.applications.result', $application) }}" method="POST" enctype="multipart/form-data">@csrf<input class="rounded-xl border border-slate-300 bg-white p-3" type="file" name="result_file" accept="application/pdf" required><button type="submit" class="rounded-xl bg-solo-blue px-5 py-3 font-black text-white shadow transition hover:bg-solo-deep">Upload surat jadi</button></form></div>@elseif($application->status === 'completed')<div class="mt-8 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">Surat hasil tersedia.</div>@elseif($application->status === 'rejected')<div class="mt-8 rounded-xl bg-red-50 p-4 text-sm text-red-700"><b>Alasan:</b> {{ $application->officer_note }}</div>@endif</aside></div></div></section>
@endsection

@push('scripts')
<script>
document.querySelector('[data-reject-application]')?.addEventListener('click', function () { this.classList.add('hidden'); document.querySelector('#reject-application-form')?.classList.remove('hidden'); });

const scrollKey = 'admin-application-scroll';
const savedScroll = sessionStorage.getItem(scrollKey);
if (savedScroll !== null) {
    window.requestAnimationFrame(() => window.scrollTo({ top: Number(savedScroll), behavior: 'instant' }));
    sessionStorage.removeItem(scrollKey);
}
document.querySelectorAll('[data-preserve-scroll]').forEach((form) => {
    form.addEventListener('submit', () => sessionStorage.setItem(scrollKey, String(window.scrollY)));
});
document.querySelectorAll('[data-reject-file]').forEach(function (button) { button.addEventListener('click', function () { button.classList.add('hidden'); document.querySelector('#reject-file-' + button.dataset.rejectFile)?.classList.remove('hidden'); document.querySelector('#reject-file-' + button.dataset.rejectFile)?.classList.add('flex'); }); });
</script>
@endpush
