@extends('layouts.app')
@section('content')
<section class="hero-gradient text-white"><div class="mx-auto max-w-7xl px-5 py-14"><p class="font-bold uppercase tracking-widest text-emerald-200">{{ now('Asia/Jakarta')->hour < 11 ? 'Selamat pagi' : (now('Asia/Jakarta')->hour < 15 ? 'Selamat siang' : (now('Asia/Jakarta')->hour < 18 ? 'Selamat sore' : 'Selamat malam')) }}, {{ auth()->user()->name }}</p><h1 class="mt-3 text-4xl font-black">Dashboard layanan digital</h1><p class="mt-3 text-blue-100">Kelola permohonan dan dokumen administrasi Anda dari satu tempat.</p></div></section>
<section class="pattern"><div class="mx-auto max-w-7xl px-5 py-12">
@if(session('success'))<div class="mb-6 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-700">{{ session('success') }}</div>@endif
@if($applications->where('status', 'rejected')->isNotEmpty())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><h2 class="font-black">Notifikasi pengajuan</h2><div class="mt-3 grid gap-3">@foreach($applications->where('status', 'rejected') as $rejected)<div class="rounded-xl bg-white/70 p-3 text-sm"><b>{{ $rejected->application_number }} · {{ $rejected->documentType->name }}</b><p class="mt-1">Alasan admin: {{ $rejected->officer_note ?: 'Pengajuan belum memenuhi persyaratan.' }}</p></div>@endforeach</div></div>@endif
<div class="grid gap-5 sm:grid-cols-3"><div class="rounded-3xl bg-white p-6 shadow-sm"><div class="text-sm font-bold text-slate-500">Permohonan aktif</div><div class="mt-2 text-3xl font-black text-solo-blue">{{ $activeCount }}</div></div><div class="rounded-3xl bg-white p-6 shadow-sm"><div class="text-sm font-bold text-slate-500">Perlu perbaikan</div><div class="mt-2 text-3xl font-black text-amber-500">{{ $revisionCount }}</div></div><div class="rounded-3xl bg-white p-6 shadow-sm"><div class="text-sm font-bold text-slate-500">Selesai</div><div class="mt-2 text-3xl font-black text-emerald-600">{{ $completedCount }}</div></div></div>
<div class="mt-8 rounded-3xl bg-white p-8 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-2xl font-black text-solo-blue">Permohonan saya</h2><p class="mt-1 text-slate-500">Pantau seluruh pengajuan layanan Anda.</p></div><a href="{{ route('services.index') }}" class="rounded-full bg-solo-blue px-5 py-3 font-extrabold text-white">Ajukan layanan baru</a></div>
@if($applications->isEmpty())
<div class="mt-8 rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">Belum ada permohonan digital.</div>
@else
<div class="mt-8 overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead><tr class="border-b border-slate-200 text-slate-500"><th class="pb-4 pr-4">Nomor permohonan</th><th class="pb-4 pr-4">Layanan</th><th class="pb-4 pr-4">Tanggal</th><th class="pb-4">Status</th></tr></thead><tbody>
@foreach($applications as $application)
<tr class="border-b border-slate-100"><td class="py-5 pr-4 font-black text-solo-blue">{{ $application->application_number }}</td><td class="py-5 pr-4 font-bold text-slate-700">{{ $application->documentType->name }}</td><td class="py-5 pr-4 text-slate-500">{{ $application->submitted_at?->format('d M Y, H:i') }}</td><td class="py-5"><span class="rounded-full px-3 py-1 text-xs font-black {{ ['submitted'=>'bg-amber-100 text-amber-700','under_review'=>'bg-amber-100 text-amber-700','needs_revision'=>'bg-orange-100 text-orange-700','approved'=>'bg-blue-100 text-blue-700','completed'=>'bg-emerald-100 text-emerald-700','rejected'=>'bg-red-100 text-red-700'][$application->status] ?? 'bg-slate-100 text-slate-700' }}">{{ str_replace('_', ' ', ucfirst($application->status)) }}</span>@if($application->status === 'submitted')<a class="ml-3 font-black text-solo-blue" href="{{ route('citizen.applications.edit', $application) }}">View / Edit</a>@elseif($application->status === 'rejected')<a class="ml-3 font-black text-red-600" href="{{ route('citizen.applications.edit', $application) }}">Perbaikan data</a>@endif @if($application->status === 'completed' && $application->files()->where('is_result', true)->exists())<div class="mt-2 flex flex-wrap gap-3"><a class="font-black text-solo-blue" target="_blank" rel="noopener" href="{{ route('citizen.applications.view-result', $application) }}">View surat</a><a class="font-black text-solo-blue" href="{{ route('citizen.applications.download-result', $application) }}">Download surat</a></div>@endif</td></tr>
@endforeach
</tbody></table></div>
@endif
</div></div></section>
@endsection
